### ISSUE TITLE
ACE needs kit assembly instructions

### ISSUE THREAD

**Issue by audrey-y** [lizzard/BAMF#19]

**Comment by craftyavenger** [comment]
We have v1 of the instructions. It won't pay to iterate until we get feed back... don't fix it until you know it is broke. 

https://drive.google.com/file/d/1BMwjOg4c94esfRKBktL0Jgt6-2cxGcYh/view?usp=sharing

**Comment by craftyavenger** [comment]
Opps wrong instructions. We have how to kit a unit instructions. We used them they work until we redefine what a "unit: is.

**Comment by audrey-y** [comment]
Oh yes, I was just playing with the tool and putting in an example. Your guide is great. But look - now I'm going to close the issue, whee.
